[package]
name        = "latticeshield-bridge"
description = "Reverse proxy TLS con cifrado hibrido PQC"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true

[[bin]]
name = "latticeshield-bridge"
path = "src/main.rs"

[dependencies]
latticeshield-crypto = { path = "../latticeshield-crypto" }
tokio              = { workspace = true }
aes-gcm            = { workspace = true }
rand_core          = { workspace = true }
anyhow                      = { workspace = true }
zeroize                     = { workspace = true }
tracing                     = { workspace = true }
tracing-subscriber          = { workspace = true }
axum                        = { workspace = true }
metrics                     = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
