[package]
name        = "latticeshield-bridge"
description = "Reverse proxy TLS con cifrado hibrido PQC"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
publish.workspace    = true
repository.workspace = true

[lib]
name = "latticeshield_bridge"
path = "src/lib.rs"

[[bin]]
name = "latticeshield-bridge"
path = "src/main.rs"

[dependencies]
latticeshield-crypto = { path = "../latticeshield-crypto" }
tokio              = { workspace = true }
rand_core          = { workspace = true }
anyhow                      = { workspace = true }
zeroize                     = { workspace = true }
tracing                     = { workspace = true }
tracing-subscriber          = { workspace = true }
axum                        = { workspace = true }
metrics                     = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
toml                        = "0.8"
clap                        = { version = "4", features = ["derive"] }
serde                       = { workspace = true }
reqwest                     = { version = "0.12", default-features = false, features = ["json", "rustls-tls-native-roots-no-provider"] }
serde_json                  = { workspace = true }
url                         = "2"
tokio-rustls                = "0.26"
rustls-pemfile              = "2"
httparse                    = "1"
quinn  = { workspace = true }
rustls = { workspace = true }
sha2   = { workspace = true }
uuid   = { version = "1", features = ["v4"] }
base64 = "0.22"

[dependencies.rcgen]
version  = "0.13"
optional = true

[features]
default    = []
tls-keygen = ["dep:rcgen"]

[dev-dependencies]
tempfile   = "3"
wiremock   = "0.6"
rcgen      = "0.13"
tokio-test = "0.4"
tower      = "0.5"
