[package]
name        = "latticeshield-crypto"
description = "Motor criptografico hibrido PQC: X25519 + ML-KEM-768 + HKDF-SHA256"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
publish              = true
repository.workspace = true

[dependencies]
ml-kem       = { workspace = true }
x25519-dalek = { workspace = true }
hkdf         = { workspace = true }
sha2         = { workspace = true }
aes-gcm      = { workspace = true }
rand_core    = { workspace = true }
thiserror    = { workspace = true }
zeroize        = { workspace = true }
hybrid-array   = "0.2"
libcrux-ml-dsa = { workspace = true }
libc           = "0.2"
tokio          = { version = "1", features = ["io-util"] }
anyhow         = { workspace = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
rand_core = { version = "0.6", features = ["getrandom"] }
tokio     = { version = "1", features = ["macros", "rt"] }

[[bench]]
name    = "pqc_benchmarks"
harness = false
